### ISSUE TITLE
Discussing TCP/IP communications in Pymodaq and with LECO

### ISSUE THREAD

**Issue by rgeneaux** [PyMoDAQ/PyMoDAQ#246] opened 2024-01-25 16:36 UTC
Hi,
Here is what we would like to do:
- Computer 1 is connected to an actuator, and runs a daq_move for it
- Computer 2 runs a proprietary software (SPECS, for an ARPES detector) which has the conveniency of being able to send tcp ip commands pretty easily, and incorporate that into its scanning routines.

So ideally we'd have a tcp/ip server on computer 1, always running. Then computer 2 connects to it whenever it wants, and sends move commands or queries the current position.

However it seems like the usual server/client behavior in pymodaq is opposite : the computer running the daq_move is the client, and it connects to the server, which sends commands. Is it possible to set it up in reverse way?

**Comment by seb5g** [comment] 2024-01-26 09:44
there is a generic TCP Server object: 
![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/aa249dc2-91dc-479a-a440-adf3996a886f)

that any existing plugin may inherit from by reimplementing some of its method you should be able to receive/send commands directly within your plugin...

But I was thinking to develop a more generic way to serve TCP IP stuff by running a server somewhere and then all other daq_move or daq_viewer or your ARPES could connect to it, we just need to route the command/data to the proper direction. I'll add @BenediktBurger as he has been working in that direction with its LECO protocol. It would be good to actually have an update on this and maybe a visio conf to discuss what could/should be done

**Comment by BenediktBurger** [comment] 2024-01-26 11:21
Thanks for pinging me.

### LECO server/client

In fact, I had tried (after the pymodaq days) to make it work via LECO.
The server side was quite simple, as they are their own plugins.
To add the client, which is written in the plugin infrastructure itself, was more complicated, as everything is connected via Signals etc.
At one point I stopped trying, as I'm quite busy with experiments.

Now I was thinking about retouching this issue (I got some ideas how to solve it) and asking for help regarding the integration. In this moment, your message arrived.

### Original topic

Maybe LECO could help:
I envision, that you can send commands between a viewer/mover plugin in the dashboard and a plugin externally. Commands could go in both directions.
In this case, your external plugin could talk via raw tcp to the instrument and via LECO to the dashboard causing actions in the dashboard/reporting values.

### Comments
> I was thinking to develop a more generic way to serve TCP IP stuff by running a server somewhere and then all other daq_move or daq_viewer or your ARPES could connect to it, we just need to route the command/data to the proper direction.

That is exactly what LECO can offer: a server and a way to route messages from one Component to another one.
You just need an individual name for each Component in the network, but at least the dashboard has already unique names for all the plugins.

> It would be good to actually have an update on this and maybe a visio conf to discuss what could/should be done

I found it quite difficult to understand, what which `ThreadCommand` does. Maybe it is better to use more differentiated signals instead of one Signal for everything.

Another option could be to add Enums with possible `command` values. That is fully backwards compatible as strings will be sent, but it might be more readable and writable.
A class could have a `Commands` enum, such that you know which commands it can accept.

**Comment by seb5g** [comment] 2024-01-26 12:24
> That is exactly what LECO can offer: a server and a way to route messages from one Component to another one. You just need an individual name for each Component in the network, but at least the dashboard has already unique names for all the plugins.
> 
Do you think, you can show us a minimal working example of a director and a few actors, from this I should be able to add this feature into the daq_moves/daq_viewers

> 
> I found it quite difficult to understand, what which `ThreadCommand` does. Maybe it is better to use more differentiated signals instead of one Signal for everything.

It is indeed complex because it will be used in various location with similar purpose but with different authorized "commands". It is also used in different "directions" like from daq_viewer towards the plugin and from the plugin towards the daq_viewer... The fact that it is quite opened and I'm not using enums is because it also allows unknown yet commands to be send and transferred directly to a method in the plugin

for instance:
![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/2657dbf9-f80e-4bf7-aa43-01e2838507a9)

will transfer the 'ROISelect' command directly to the plugin if the plugin implement the method ROISelect and is generalized by:
![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/ec17d8eb-2a89-4649-b865-012da9901218)


But I agree that it should offer some more introspection...

**Comment by seb5g** [comment] 2024-01-26 12:27
> I found it quite difficult to understand, what which `ThreadCommand` does. Maybe it is better to use more differentiated signals instead of one Signal for everything.

Actually this may be a good choice, like creating a subclass of Threadcommand that has a meaningfull name given its purpose, like `ControlToPluginCommand` for instance

**Comment by BenediktBurger** [comment] 2024-01-26 13:02
> The fact that it is quite opened and I'm not using enums is because it also allows unknown yet commands to be send and transferred directly to a method in the plugin

With the enums, I did not mean to change the `ThreadCommand` itself (its `command` parameter is still a string), but to offer a collection of possible commands without limiting the commands to members of that enum.
For example a `enum.StrEnum` (or in python versions<3.11 `class StrEnum(str, Enum)`) is quite useful for that purpose.

**Comment by seb5g** [comment] 2024-01-26 13:20
and what about declaring a list of possible commands as a tuple (or a StrEnum) as a class member of let's say `ControlToPluginCommand ` and other subclassed ThreadCommands? Would that help?

**Comment by BenediktBurger** [comment] 2024-01-26 13:26
Class members of Thread command (subclasses) would be another idea. I like it.

Having such an enum / class variable etc. Helps to avoid typos in the strings, which are hard to find bugs.

Here is my test version of a server using leco: https://git.rwth-aachen.de/nloqo/thg/pymodaq_plugins_thg/-/blob/ae669cde3d7a3333d7c52f098f4a533085a6056b/src/pymodaq_plugins_thg/daq_viewer_plugins/plugins_2D/daq_2Dviewer_LECOServer.py

In my "leco-test" branch in my pymodaq fork I have my intends for a client (I have to update it to the newest pyleco version though, as my work on pymodaq prompted some changes to pyleco).

**Comment by seb5g** [comment] 2024-01-26 13:44
I can't access your private git page!

**Comment by BenediktBurger** [comment] 2024-01-26 14:10
I changed it to public.

**Comment by BenediktBurger** [comment] 2024-02-01 18:06
By the way, pyleco is now on pypi, which should make it easier to use it.

**Comment by rgeneaux** [comment] 2024-02-06 18:20
Before trying the pyleco objects I've been trying to play with the built-in TCPServer and Clients to connect two clients togehter, through a server, managed to do that:

![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/295505/6ad72881-e85a-4b39-9035-e09306938f9f)

I noticed that CPU usage gets pretty high when connecting these two clients (noticed my computer fan going a bit crazy) and I wonder if this loop is the culprit:
![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/295505/07f4c5d5-0754-4568-ac61-0137938e3713)

When we don't do anything, the two clients are always ready to write and thus the loop gets done very fast. Am I missing something?

**Comment by seb5g** [comment] 2024-02-06 20:06
I'm pretty sure you're right!
To be honest I'm not a professional of sockets and I wrote this like this from gist not knowing if this would be the best implementation. This is also why I would fall back on a more professional implementation such as LECO (well after testing it of course :-) )

Saying this, you should try to add a temporisation using ``QThread.msleep(10)`` at the end of the loop

**Comment by seb5g** [comment] 2024-02-06 20:32
> Class members of Thread command (subclasses) would be another idea. I like it.
> 
> Having such an enum / class variable etc. Helps to avoid typos in the strings, which are hard to find bugs.
> 
> Here is my test version of a server using leco: https://git.rwth-aachen.de/nloqo/thg/pymodaq_plugins_thg/-/blob/ae669cde3d7a3333d7c52f098f4a533085a6056b/src/pymodaq_plugins_thg/daq_viewer_plugins/plugins_2D/daq_2Dviewer_LECOServer.py
> 
> In my "leco-test" branch in my pymodaq fork I have my intends for a client (I have to update it to the newest pyleco version though, as my work on pymodaq prompted some changes to pyleco).

@BenediktBurger , could you tell me how I should start : your pymodaq_leco_server (is that a coordinator?) and then make a real control module (an actor) and a "fake one" (another actor but without any  instrument linked to it) communicate over this Coordinator?

Rather than me understanding in depth pyleco to try to implement it (like you just almost did) what do you deem important for me to help with? I can work on the ThreadCommand stuff (wherever it is used)! What else?

**Comment by BenediktBurger** [comment] 2024-02-06 22:44
Probably we need to unite our knowledge of our own code base to make the integration work.

## Building blocks of pyleco

I describe the building blocks of pyleco, that you might understand better, how they could be integrated in pymodaq:
- The Coordinator just routes messages between Components. It's infrastructure. Basically, You just need to run it anywhere. Maybe it is good to include one as an extension to make it simpler. For development (or an existing infrastructure), just start it (executing the Coordinator.py module).
- the "CommunicatorProtocol" is an interface definition to send messages via leco to other components. There are several pyleco utils which could be used.
- the Message Handler runs in an infinity loop, listening for incoming messages. Whenever one arrives, it handles the message: it executes the method specified in the message and sends the return value to the sender of the message. The Message Handler satisfies the Communicator Protocol and is therefore able to send messages to other components and reading the answer (for example due to a timer).
- The Listener runs a Message Handler in a separate thread. That allows the main program to continue doing whatever it does. The Listener offers a Communicator, which sends messages (and reads the response) via the Message Handler. On the other hand, the Message Handler can react to incoming messages, for example read a Value of the main program and return it to the asking program.
- the qtListener is a Listener which emits a qt signal, whenever a message arrived.

## basic ideas for pyleco in pymodaq

Here my design ideas for integrating leco into pymodaq:
- each plugin has its own Listener (probably the at version or some modification thereof) 
- each component needs its own name, but the plugin name is already unique, so we can use the plugin name as component name
- include an (optional) coordinator as an extension

## Concept of pyleco

The idea of Rpc (remote procedure call) is, that you call methods / procedures remotely.
Therefore, we have to define methods, which could be called remotely.

Here an example from instrument control: the Actor (controlling some insteument) offers some method "get_value_x", which returns the value x of the device, for example
~~~python
def return_value_x(self):
    return self.device.x
~~~
Now, if we want to know the value of x, we call that method remotely and get it's return value.

## Prepare pymodaq for pyleco

The most simple configuration would be, if each plugin had a collection of methods. These methods could do things (connecting, starting a scan... ), set values or get values.

If that is done, leco support is easy: you register these methods with the Message Handler.
Now you can call these methods from any other plugin.

There are some caveats, though:
Let's assume we have a central dashboard and some remote plug-ins with devices.
The dashboard can read the device plug-ins or set there some value (which triggers device interaction).
However, if the device plugin wants to inform the dashboard about some change (e. G. A new value), it has to know the name of the corresponding plugin.
That way, it can call the "show_recent_value" method of the dashboard plugin, which will show that value.

Alternatively, we could use the data protocol: The external plug-ins publish their status updates and the dashboard plug-ins subscribe (the Listener has that feature built in: whenever a data message of a subscribed channel arrives, a qt signal is emitted).

## Final words

I hope I could help clarify the usage a little bit.
By the way, the pyleco release contains a ["getting started"](https://github.com/pymeasure/pyleco/blob/main/GETTING_STARTED.md) file, which could help with the start. Additionally, I added a description of my setup in the [discussions](https://github.com/pymeasure/pyleco/discussions/46) in the pyleco repo. 


## Development branch (EDIT)

In the [leco-test](https://github.com/BenediktBurger/PyMoDAQ/tree/leco-test) branch of my fork, I have both types of plugin (modeled similar to the TCP server/client), in order to have a single branch for development.
When it works, we can move them out in a separate plugins package.

**Comment by rgeneaux** [comment] 2024-02-07 08:28
Thanks Benedikt! 
Do I follow correctly: each control module in pymodaq could be one of two things: 
- a plugin connected locally to a real instrument but that we might control remotely, thus it will declare an Actor (does the Actor have a built-in Listener?)
- a plugin that only sends commands to a remote Actor (via the Coordinator) and displays data received (current position for a daq_move, data for a viewer), and thus only needs to declare a Listener

> the plugin name is already unique, so we can use the plugin name as component name

Which plugin name do you mean? the class name doesn't work since we can instantiate several. perhaps the *title* property of each control module instance? Then the user would have to make sure they are unique in a dashboard preset, but that could be ok.

**Comment by BenediktBurger** [comment] 2024-02-07 08:55
## Introduction

There are two different use cases for LECO:
1. Current pymodaq dashboard with a plugin, which uses LECO to communicate with a LECO Actor (which is not a pymodaq control module) controlling an instrument. This kind of plugins is in [pymodaq_plugins_leco](https://github.com/pymeasure/pymodaq_plugins_leco), created during pymodaq days.
   These kinds of plugins have to be written for every instrument anew.
2. We make control modules communicate among each other, similar to the current tcp implementation. This would make it possible, to have a local module in the dashboard communicating with a control module remotely. The remote control module communicates with a device locally, that means, it can be from any regular plugins page

The first case is easy, but not that useful (new plugins for many instruments).
We are currently working on the second use case of LECO, to enhance all present plugins.

## Comments

### Name definitions

> Do I follow correctly: each control module in pymodaq could be one of two things: ...

Let's call the module in the dashboard **director module** and the other one, controlling the instrument, **actor module**.

EDIT: local and remote changes from the perspective of the module, with director (dashboard) and actor (instrument), the naming is better.

### Actor Module

> a plugin connected locally to a real instrument but that we might control remotely

Yes, exactly.
We could call it an Actor (as it acts), but it will not use the `Actor` class (which is specialized in instrument control).
However, it is not a mere actor, as changes in this remote module should change the local module as well.
Unless we block the GUI for changes (make them read only)

> does the Actor have a built-in Listener?

The `Actor` class of PyLECO is a subclass of the MessageHandler. we do not need it in this case, as we want to communicate between control modules, not with instruments (directly).
As a MessageHandler, it runs in an infinity loop.

Here a Listener comes handy as well, as it will make the communication in an extra thread, keeping the GUI responsive.

### Director Module

> a plugin that only sends commands to a remote Actor (via the Coordinator) and displays data received (current position for a daq_move, data for a viewer), 

Exactly. However remote changes should be shown here as well

> and thus only needs to declare a Listener

Yes, a Listener would be good tool.

## Names

> Which plugin name do you mean? the class name doesn't work since we can instantiate several. perhaps the title property of each control module instance? Then the user would have to make sure they are unique in a dashboard preset, but that could be ok.

I thought about the title.
The title is not unique?

I think using the title will make it the most simple setup, as a user will know, which module is which one.

EDIT: Looking at the code, I think it is called `module_name`, isn't it?

**Comment by BenediktBurger** [comment] 2024-02-07 09:59
The PR #264 contains the files of the 'leco-test' branch.

This branch should be self sufficient (no need for other repositories) for the development.
Initially with a ViewerDirector (analogous to the TCP Server) and modifications to the viewer plugin to work as a Actor (analogous to the TCP Client).

Maybe it helps understanding, what I intended to do.

**Comment by BenediktBurger** [comment] 2024-02-07 15:55
Update: I made the "Client" (in TCP version) or the Actor (in pyleco terms) halfway working (at least the move):
You can start a mock move plugin and with the Director (in director_utils) you can move the mock move.
Whenever the mock move finished moving, it will try to call a method of the Director, setting the value there.

**Comment by rgeneaux** [comment] 2024-02-08 10:09
I wanted to check it but I can't figure out how you run the Director! is it a daq_move?

**Comment by BenediktBurger** [comment] 2024-02-08 10:26
No the Directors (in the director_utils) are pyleco tools.

You can use them alone or in other code (e.g. the moveLECOServer).
Let's assume you have the Coordinator up and running, and you have a MockActuator started.
In the MockActuator you have started the "connect leco" option (main settings, similar to a TCP client).
Let's assume the module_name (string given to the actual module) is "name_given_to_actuator_plugin".

Now you can run
~~~python
from pymodaq.utils.leco.director_utils import ActuatorDirector

with ActuatorDirector(actor="name_given_to_actuator_plugin") as director
    director.move_rel(10)

# or:
director = ActuatorDirector(actor="name_given_to_actuator_plugin")
director.move_rel(10)
# do whatever you wish ...
director.close()
~~~
which would move the the Mock by 10 units.

What these pyleco Directors do, they provide methods to call (such that the user does not have to remember the name strings of the remote methods and their parameter names).
If you do not provide a Director with a Communicator (like here, on contrary, the moveLECOServer gives the Listener's communicator), the Director will create its own Communicator, sign in and (if used as a context manager) sign out at the end.

**Comment by BenediktBurger** [comment] 2024-02-08 10:56
I wrote a short introduction to the code and how it works in the PR #264 . I hope it helps understanding, how it works.

**Comment by rgeneaux** [comment] 2024-02-08 13:26
Much clearer, thanks! I was able to control the remote Mock stage from a script like you described. 

Now, also with the "DAQ_Move_LECODirector" (indeed in a plugin folder), after a few typo fixed, it works!
![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/295505/bcf6ff34-a251-4524-966e-3dfc99c787c0)

Importantly, to make the mock stage move you need to set `data_actuator_type = DataActuatorType['float']` for "DAQ_Move_LECODirector", otherwise it tries to send objects of more complex type (DataActuator) and that causes "PydanticSerializationError"

I think that before continuing we should make a proper plugin repository and write the DAQ_Move_LECODirector (and then the viewers) cleanly from the up-to-date template, right now it is in a bit of a weird mixed state

**Comment by BenediktBurger** [comment] 2024-02-08 13:47
> I think that before continuing we should make a proper plugin repository and write the DAQ_Move_LECODirector (and then the viewers) cleanly from the up-to-date template,

I had already created a repo in the pymeasure organization, as it is related to pyleco (also in pymeasure).
However, as it is going to be an essential part of pymodaq (replacing tcp server etc., maybe being preinstalled like the mocks), maybe the pymodaq organization is better.
@seb5g , what do you think?

>  right now it is in a bit of a weird mixed state

The mixed state is a consequence, that we have to change plugins and the core pymodaq at the same time.

> Importantly, to make the mock stage move you need to set data_actuator_type = DataActuatorType['float'] for "DAQ_Move_LECODirector", otherwise it tries to send objects of more complex type (DataActuator) and that causes "PydanticSerializationError"

Ah yes. I already have an idea, how to transport these objects (needed for the viewer). @seb5g already made serializers, which we can use.

Thanks for working together.

**Comment by seb5g** [comment] 2024-02-08 21:35
I couldn't find the time to test it yet but that's quite exciting. If we go and use it as the main remote communication protocol, then the DAQ_Move_LECODirector (and then the viewers) should really be hosted into a given plugin on pymodaq organisation to make sure it is easy to have them evolve together with pymodaq! @rgeneaux , you're free to create a new plugin from the up to date template repository.

As for the Serialization, these object should be able to be send as messages. I have to check that the DataActuator is actually properly serialized but it's inheriting from DataWithAxes so should be fine (I created the DataActuator after I did the serialization)!

**Comment by BenediktBurger** [comment] 2024-02-08 21:54
Actually (during a long measurement) I started to implement to use the serialization.

So it is coming together.

**Comment by BenediktBurger** [comment] 2024-02-09 12:11
> Now, also with the "DAQ_Move_LECODirector" (indeed in a plugin folder), after a few typo fixed, it works!

@rgeneaux  could you indicate the typos? I cannot get the Director interface to work (it shows the values, but the setters of position etc. are disabled).

EDIT: I got it.

**Comment by BenediktBurger** [comment] 2024-02-12 17:22
By the way: For development, I left the plugins in that LECO folder, but put some dummy importers in a plugin folder:
~~~python
from pymodaq.utils.leco.daq_1Dviewer_LECODirector import DAQ_1DViewer_LECODirector, main

if __name__ == '__main__':
    main(__file__)
~~~

**Comment by BenediktBurger** [comment] 2024-02-12 17:22
Update: Move works now, also 0D viewer.

**Comment by BenediktBurger** [comment] 2024-02-12 17:42
My branch works now (at least in my simple test scenarios) for all the plugin types.

You know better all the capabilities. Maybe you could test it as an alternative to TCP.

I'll be glad to help refactoring it, but I do not know the use cases.

**Comment by BenediktBurger** [comment] 2024-02-12 17:54
By the way, I used the serialized objects, which makes transfer easy (I did not have to worry about the pymodaq objects).

Thanks @seb5g

**Comment by seb5g** [comment] 2024-02-13 12:19
Thanks for this huge work. I'm holiday right now but will be testing it when I'm back

**Comment by seb5g** [comment] 2024-02-22 21:47
Thanks to the huge work by @BenediktBurger  the leco protocol is functional. I managed to run a dashboard with mock instruments (beam steering kind) and control it from a dashboard having similar instrument but only directors. I could easily do a scan from the director dashboard. The initial goal of pairing any instrument with any 'server' is officially done!!!
You can also simply pair from a standalone control module to a stand alone director, any combination is working.

PR #275 is also enabling easy coordinator running

To my opinion, the few things to work on are:

*  to synchronize the settings (something the TCP/IP legacy stuff is still doing) 
* manage the fact that pyleco is only running on python >= 3.9 (this is kind of sad as it would be very helpful to connect old    computers where only old python version may work), I have this issue on a 32 bits python where version 3.7 is the only one I   could install

Anyhow, @rgeneaux I suggest you try this for your use case!

**Comment by seb5g** [comment] 2024-02-22 21:51
actually @BenediktBurger there are still CI issues with python 3.9, could you try to run the CI tests on python 3.9 and check it (see below but only for py39)?

![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/2fbb3ecb-6c82-4388-b44a-b2a37e023196)

**Comment by BenediktBurger** [comment] 2024-02-22 22:33
I guess the problem is, that I check, whether the object is an instance of Union, which is probably valid for python > 3.9.

I can try to create a "pyleco light" version without the dependency.
It will be reduced in comfort and content (maybe without the Coordinator), but should work as well.

I have to see, how to release it.

**Comment by seb5g** [comment] 2024-02-23 08:12
maybe you can create a function with almost the same simplicity but hiding a more complex isinstance mechanism. I think it is important we try to stay as much compatible with old python version and I know that typing has evolved the most in between 3.7-> 3.10 creating various issues

**Comment by BenediktBurger** [comment] 2024-02-23 08:21
> I guess the problem is, that I check, whether the object is an instance of Union, which is probably valid for python > 3.9.

PR #276 

> maybe you can create a function with almost the same simplicity but hiding a more complex isinstance mechanism. I think it is important we try to stay as much compatible with old python version and I know that typing has evolved the most in between 3.7-> 3.10 creating various issues

I have an idea how to replace the dependency (at least for older python versions).

**Comment by seb5g** [comment] 2024-05-27 18:09
pyleco is now compatible with python version 3.8 and earlier. For older version one should use the legacy TCP/IP stuff

**Closed as completed by seb5g** 2024-05-27 18:09 UTC
