### ISSUE TITLE
master_controller not initialized.

### ISSUE THREAD

**Issue by bmoneke** [PyMoDAQ/PyMoDAQ#175] opened 2023-10-23 14:31 UTC
During the work of #174 I found another bug in dashboard.py:

https://github.com/PyMoDAQ/PyMoDAQ/blob/b870fef0f612a703d44abb797cba2f18c4282fa2/src/pymodaq/dashboard.py#L744-L818

How to reproduce:
1. open the dashboard
2. Change the beam_steering_mock to not initialize the camera (but the actuators)
3. Load the preset
4. Find the following error in the log:

~~~
pymodaq.dashboard - ERROR - cannot access local variable 'master_controller' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\moneke.NLOQO\Repositories\PyMoDAQ\src\pymodaq\dashboard.py", line 772, in set_file_preset
    actuators_modules[-1].controller = master_controller
                                       ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'master_controller' where it is not associated with a value
~~~

I guess the problem is, that the first plugin is the camera. Without initializiation, there is no `master_controller` yet.

I don't know, what you expect to happen instead.

**Comment by bmoneke** [comment] 2023-10-27 07:31
I find it confusing, that there is a difference, whether I check "init" in the preset or doing it afterwards.

As a user I expect the preset to load independent of the init state of hardware.

**Comment by rgeneaux** [comment] 2023-10-27 07:44
Hi,
In this preset there is master/slave behavior (camera is the master) to be
able to simulate the beam moving on the camera, when the actuators are used.

So I think what you see is normal behavior and not a bug, it makes sense
that the slave cannot be initialized if the master isn't yet. You will have
the same error if you launch the preset without initializing anything, and
try to initialize the motors before the camera.

Le ven. 27 oct. 2023, 09:31, Benedikt Burger ***@***.***> a
écrit :

**Comment by seb5g** [comment] 2023-10-27 07:48
This is a really particular case for these master/slave controllers. 

The control modules should b initialized in the right order: first master, then slave with slave receiving an instance of the master controller. Therefore the slave doesn't have to reopen a communication already opened by the master. They will share the same communication resource. 

If the master module is not initialized there is no way for the slave to know how to init. But you are right, **it is important for the user to at least be notified that there was an issue related to master/slave configuration**. In this case, a message popup should be raised to let know the user. 

In PR #174 a possibility was discussed: 

* add a try statement in each module initialization
* log the error, and raise an other error (ActuatorError/DetectorError) that will trigger a message and the closing of the application (as the user should modify their preset)

Other ideas?

**Comment by bmoneke** [comment] 2023-10-27 07:52
Now I understand it better. The example preset has the camera as a master.
Ok, that makes sense, that you cannot load it, if the camera is not initialized.

I'm fine with a message stating, that you try to initialize slaves without an initialized master. That should hint at the right issue.

In the current code base, though, the preset loading hangs (because of an uncaught exception) and you do not know, why.

**Comment by bmoneke** [comment] 2023-10-27 08:26
A few notes trying to implement a stop-gap measure in #173 and looking at the code

- if a DetectorError (or ActuatorError) is raised (I tried catching the NameError and raising such an error), the message box (for example of line 815) is not shown, because the return a few lines later is different from the expected return value, as I get the following error in the log:
  ~~~
  pymodaq.dashboard - ERROR - cannot unpack non-iterable NoneType object
  Traceback (most recent call last):
    File "...PyMoDAQ\src\pymodaq\dashboard.py", line 1104, in set_preset_mode
      actuators_modules, detector_modules = self.set_file_preset(filename)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: cannot unpack non-iterable NoneType object
  ~~~
- what happens if I have two masters and each has at least one slave. Let's assume, that the first master is initialized, then "master_controller" is defined. The second master, however, is not initialized. In this case, the slave of the second master will point to the first master!
- The code for both plugin types seems quite similar, could it not be made a single method?

**Comment by seb5g** [comment] 2023-10-27 12:05
as for your first question, master/slave that should work together must have the same controller ID, see:

http://pymodaq.cnrs.fr/en/latest/modules/DashBoard.html#multiple-hardware-from-one-controller for a better understanding.

So basically the dashboard knows which module is slave of which master. 

For the second question, I think the solution should be to actually catch the error in the parent method (set_preset_mode):
![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/f86e95e2-2ad0-4c40-ba2e-b6f2b3734c33)

and in there quitting the application. Because as it is now, it doesn't return the right tuple (just a bare return) and even if it returned a tuple of empty lists it would try to close the modules while processing the rest of the parent method (set_preset_mode). 

is that clear ;-) ?

**Comment by seb5g** [comment] 2023-11-19 18:00
PR #199 fixe this issue

**Closed by seb5g** 2023-11-19 18:00 UTC
Labels: bug
